### ISSUE TITLE
User can request and receive an array of all available fighters and their information.

### ISSUE THREAD

**Issue by DreSean-Sutton** [DreSean-Sutton/Final-Project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can send a `get` request to `api/fighters` and receive an array of all available fighters and their basic information.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Whether through the `CLI` or as an AJAX request in their own application, users will be able to submit a `get` request to the `/api/fighters` path of my server and receive an array of JSON data models. Each model will have basic information that pertains to that specific fighter.
## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Drop schema `public cascade` (For now).
- [x] Create schema named `public`
- [x] Create several tables
  - [x] `public.fighters` table with:
    - [x] `fighterId SERIAL`
    - [x] `fighter TEXT NOT NULL`
    - [x] `rosterId TEXT NOT NULL`
    - [x] `displayName TEXT NOT NULL`
    - [x] `createdAt TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()`
    - [x] `PRIMARY KEY("fighterId")`
  - [x] `public.moves` table with:
    - [x] `moveId SERIAL`
    - [x] `fighterId INT REFERENCES public.fighters`
    - [x] `name TEXT NOT NULL`
    - [x] `moveType TEXT`
    - [x] `createdAt TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()`
    - [x] `PRIMARY KEY moveId`
  - [x] `public.hitboxes` table with:
    - [x] `moveId SERIAL REFERENCES public.moves`
    - [x] `damage TEXT`
    - [x] `activeFrames TEXT`
    - [x] `totalFrames TEXT`
    - [x] `createdAt TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()`
- [x] Use multiple `INSERT INTO` statements.
  - [x] `INSERT INTO public.fighters` with `name`, `rosterId`, and `displayName` as parameters
  - [x] `INSERT INTO` public.hitboxes AS (fighter name) with, `damage`, `activeFrames`, and `totalFrames` as parameters.
  - [x] INSERT INTO public.moves AS (fighter name) with `fighterId`, `name`, and `moveType` as parameters
- [x] Create a backup database and put all `schema.sql` & `data.sql` code in it. *Just in case*

### ☁️ Server

- [x] `require` all required packages.
- [x] Towards the bottom, call the use method of app with `errorMiddleware` as it's argument.
- [x] Listen on `process.env.PORT`
- [x] Call the `get` method of `app` at the `/api/fighters` path and in the code block:
  - [x] Query for all fighters and return an array of objects with each fighter's basic information.
  - [x] Send a 200 status code and a `json` response back to the client.
- [x] Throw and catch errors where possible and respond to client with the correct status codes.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client
- [x] Add SwaggerDoc's documentation comments to code that requires it.

### 🧑‍⚕️ Clean Up

- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
