### ISSUE TITLE
Feature 6: User can choose to receive only one type of data

### ISSUE THREAD

**Issue by DreSean-Sutton** [DreSean-Sutton/Final-Project#11]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can choose to receive only on type of data
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will be able to send a get request to `api/fighters/data/:type` and only receive that type of data. :type can be either `moves` or `throws`. The user can also use query parameters to specify a single fighter.
## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [ ] Add at least one Fighter to the database

### ☁️ Server

- [x] Add a new path to `api/fighters/data/:type` in `server/index.js` and inside of it:
  - [x] Take the user's req parameter
  - [x] Call query function depending on which type was input
  - [x] Throw an error if the type is invalid
  - [x] Make a SQL query with the return of the SQL function
  - [x] Respond to the user with the correct status message
  - [x] Catch any errors
- [x] Update SwaggerDocs to reflect the change
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### 🧑‍⚕️ Clean Up

- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
