### ISSUE TITLE
Feature 7: User can now see movement type data

### ISSUE THREAD

**Issue by DreSean-Sutton** [DreSean-Sutton/Final-Project#12]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can now see movement type data
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will be able to see movement type data at `api/fighters/data`. They will also be able to see only movement type data if they send a get request to `api/fighters/data/:type` if they use `movements` as the path parameter.
## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Create two new tables
  - [x] One named `movements`
    - [x] it should have `fighterId`, `movementId`, `name`, `type`
  - [x] One named `dodging`
    - [x] It should reference `movements` via `movementId`
    - [x]  Have `movementId` (serial), `activeFrames` and `totalFrames` as columns
    - [x] `activeFrames` and `totalFrames` should be text and NOT NULL
- [x] Update all characters in the database by adding their movement type data

### ☁️ Server

- [x] Update `api/fighters/data/:type` to now accept `movements` as a valid parameter
- [x] Update `sql-queries.js` module to return a SELECT query if 'movements' is passed into it as an argument
- [x] Update SwaggerDocs to reflect the change
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### 🧑‍⚕️ Clean Up

- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
