### ISSUE TITLE
Feature 8: User can see stat type data

### ISSUE THREAD

**Issue by DreSean-Sutton** [DreSean-Sutton/Final-Project#13]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see stat type data #13

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
The user will be able to see stats type data at `api/fighters/data`. They will also be able to see only stats type data if they send a get request to `api/fighters/data/:type` if they use stats as the path parameter.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Create two new tables
  - [x] One named `miscellaneous`
    - [x] It should have `statId`, `name`, and `statValue` as its columns
    - [x] It should reference `stats` via `statId`
    - [x] `name` and `statValue` should both be TEXT NOT NULL
    - [x] `statId` should be serial 
    - [x] `name` and `statValue` should be TEXT NOT NULL
  - [x] One named `stats`
    - [x] It should have `statId`, `fighterId`, `name`, and `type` as its columns
    - [x] `statId` should be serial
    - [x] `fighterId` should be INT and reference `public.fighters`
    - [x] `name` and `type` should both be TEXT NOT NULL

### ☁️ Server

- [x] Update `api/fighters/data/:type` and `api/fighters/data` path to now show stat type data
  - [x] `api/fighters/data/:type` will accept stats as a valid path parameter
  - [x] Update sql-queries.js module to return a SELECT query if 'stats' is passed into it as an argument
- [x] Update SwaggerDocs to reflect the change
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### 🧑‍⚕️ Clean Up

- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
