### ISSUE TITLE
Feature 9: User can add fighters to the database

### ISSUE THREAD

**Issue by DreSean-Sutton** [DreSean-Sutton/Final-Project#17]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add fighters to the database
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Create 5 post routes in server/index.js
  - [x]  `api/add/fighters` will handle fighters table.
  - [x] `api/add/moves` will handle the `moves&hitboxes.js` tables.
  - [x] `api/add/throws` for `throws&grappling.js` tables.
  - [x] `api/add/movements` for `movements&dodging.js` tables.
  - [x] `api/add/stats` for `stats&miscellaneous.js`  tables.
- [x] Make a conditional in each route that checks to to see if all required parameters are there
- [x] Make sure the `typeof` is correct for each parameter
- [x] In `api/add/fighters`
  - [x] Send an INSERT INTO query request to the database
  - [x] If any of the values already exist, tell the user
- [x] In the other tables:
  - [x] Recursively send two INSERT INTO query request to the database
  - [x] If any of the values already exist or aren't present, tell the user
  - [x] Assign the properties from each response into a variable and respond to the user with it
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client
- [x] Update SwaggerDocs

### 🧑‍⚕️ Clean Up

- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
