### ISSUE TITLE
Feature 10: User can update Fighters in the database

### ISSUE THREAD

**Issue by DreSean-Sutton** [DreSean-Sutton/Final-Project#18]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [ ] Try to add at least one character to the database

### ☁️ Server

- [x] Update `server/index.js`  with 5 new routes
- [x] In each route:
  - [x] Make sure the user input correct parameters and that number values are numbers.
  - [x] Check if all parameter values are valid
  - [x] Throw and error and tell them if they made any errors
  - [x] Make an update request to their respective tables
  - [x] If the update is a success
    - [x] Give a 200 status code
    - [x] Respond to the user with the updated information
    - [x] Catch any errors
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client
- [x] update SwaggerDocs with the new paths

### 🧑‍⚕️ Clean Up

- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
