### ISSUE TITLE
Feature 11: User can delete Fighters from the database

### ISSUE THREAD

**Issue by DreSean-Sutton** [DreSean-Sutton/Final-Project#19]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can delete Fighters from the database
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will be able to send a delete request to `api/delete/:table/:id` and delete data directly from the database
## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Add a Fighter to the database

### ☁️ Server

- [x] Update `server/index.js` with a route at `/api/delete/:table/:id`
- [x] With that route
  - [x] Create 5 delete functions that are only executed if `:table` is equal to that data type
  - [x] In each function, query their specific type and delete that id from the database
  - [x] Make sure referenced tables are also deleted
  - [x] Throw errors if the id doesn't exist
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client
- [x] Update SwaggerDocs

### 🧑‍⚕️ Clean Up

- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
