### ISSUE TITLE
Feature 12: User can see firstFrame data

### ISSUE THREAD

**Issue by DreSean-Sutton** [DreSean-Sutton/Final-Project#23]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see firstFrame data
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

While receiving a Fighter's moves, the user will also be able to see firstFrame data as a property on the data model
## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Add `firstFrame` data to all code in the `hitboxes` table

### ☁️ Server

- [x] Update all routes including moves data to also include the new `firstFrame` property 
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### 🧑‍⚕️ Clean Up

- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
