### ISSUE TITLE
Feature: User can request an object with only a single fighter's basic information 

### ISSUE THREAD

**Issue by DreSean-Sutton** [DreSean-Sutton/Final-Project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can request an object with only a single fighter's basic information 
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
Sending a get request to `api/fighters` will also allow the user to include a query string. It can be `fighterId`, `rosterId`, or `fighter` name and will only respond with that fighter's information.

The user will 
## 🖼️ Wireframes
![image](https://user-images.githubusercontent.com/90172283/163313110-e1ad26bb-9437-4996-8e8a-89a9a93b6195.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Add three or four new fighters to the database.

### ☁️ Server

- [x] Require `ClientError` in server/index.js
- [x] Update get `/api/fighters` function in `server/index.js` 
  - [x] Add 3 new sql queries for `rosterId`, `fighterId`, and `fighter` that only execute if the query key equals them
  - [x] Make sure client errors are thrown if query values aren't in the database
  - [x] If query key isn't correct, then throw an error and tell the user
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client
- [x] Update SwaggerDocs to let users know about the query string

### 🧑‍⚕️ Clean Up

- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
