### ISSUE TITLE
Feature 3: User can view the frame data of all available Fighters

### ISSUE THREAD

**Issue by DreSean-Sutton** [DreSean-Sutton/Final-Project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can send a get request to `api/fighters/data` and receive a json object of all fighters and their frame data.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will be able to to also see a character's frame data 
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/90172283/163607708-13bfddb3-9d82-455e-9f46-b274d9d95b21.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to include a function that listens for GET requests at `api/fighters/data` and inside of it:
  - [x] Create a sql query that SELECTs `fighterId`, `rosterId`, `fighter`,  `displayName`,  `name`,  `damage`, `activeFrames`, `totalFrames`, and `moveType` and assign it's value to the variable `sql`.
  - [x] Respond to the client with the query result
  - [x] Catch any errors
- [x] Update SwaggerDocs
- [x] Test with HTTPie
- [x] Handle any leftover errors and respond to the client

### 🧑‍⚕️ Clean Up

- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
