### ISSUE TITLE
Feature 4: User can specify which Fighter they receive frame data from

### ISSUE THREAD

**Issue by DreSean-Sutton** [DreSean-Sutton/Final-Project#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can specify which Fighter they receive frame data from
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When send a get request to `api/fighters/data`, they can use `fighterId`, `rosterId`, or `fighter` name as queries and will receive only a single fighter's frame data.
## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `api/fighters/data` route in `server/index.js` to now accept `fighter`, `fighterId`, and `rosterId` as query strings.
- [x] Modularize all template literal sql code, aside from there WHERE clause, and store it as a method on a class in their own file.
- [x] Add the ability for users to sort `api/fighters` and `api/fighters/data` by `rosterId`
- [x] Update SwaggerDocs to reflect the change.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### 🧑‍⚕️ Clean Up

- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
