### ISSUE TITLE
Feature 5: User can receive throw type data

### ISSUE THREAD

**Issue by DreSean-Sutton** [DreSean-Sutton/Final-Project#9]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can now see throw typed of data
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When receiving frame data from all Fighters or a single one, the user will now receive their throw data as well.
## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Add throw data to the database by:
  - [x] Create a table for `public.throws`
    - [x] Table should have `throwId`, `fighterId`, `name`, and `type` as columns
  - [x] Create another table for `public.grappling`
    - [x] Table should have `damage`, `activeFrames`, and `totalFrames`
  - [x] Create a `throws-data.sql` file
    - [x] Add INSERT INTO for each Fighter
    - [x] INSERT INTO column names should be `fighterId`, `name`, and `type`
  - [x] Create a `grappling-data.sql` file
    - [x] Add INSERT INTO for each Fighter
    - [x] INSERT INTO column name should be `throwId`, `damage`, `activeFrames`, and `totalFrames`
  - [x] Add `type` property to all rows in `public.moves`.
- [x] Add throw data to all Fighters
- [x] Add at least one more fighter to the database
- [x] Update data.sql

### ☁️ Server

- [x] Update `api/fighters/data` in `server/index.js` to show the type property of all frame data
- [x] Update `api/fighters/data` routes to also query for the throw data for all characters
- [x] Update SwaggerDocs to reflect the change.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### 🧑‍⚕️ Clean Up

- [x] Remove all console logs.
- [x] Remove all commented out code.- [ ] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
